services:

  mysql:
    image: mysql:8.0
    container_name: employee-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: employee_db
      MYSQL_USER: employee
      MYSQL_PASSWORD: employee123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build: ./backend/employee-app
    container_name: employee-backend
    ports:
      - "8081:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/employee_db
      SPRING_DATASOURCE_USERNAME: employee
      SPRING_DATASOURCE_PASSWORD: employee123
    depends_on:
      - mysql

  frontend:
    build: ./frontend
    container_name: employee-frontend
    ports:
      - "8090:80"
    depends_on:
      - backend

volumes:
  mysql_data: